server:
  port: 8888



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/islittlechen/git-config-repo.git
          label: master
          username: aaa
          password: bb
          search-paths: bus-refresh-config,api-integration-config,api-gateway-config,eureka-server-config,api-consumer-config
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost
    bus:
      trace:
        enabled: true
management:
  security:
    enabled: false
